#!/bin/sh

core=`cat ucengine/src/core/*.erl | wc -l`
controllers=`cat ucengine/src/controllers/*.erl | wc -l`
helpers=`cat ucengine/src/helpers/*.erl | wc -l`
models=`cat ucengine/src/models/*.erl | wc -l`
backends=`cat ucengine/src/backends/**/**/**.erl | wc -l`
tests=`cat ucengine/src/tests/*.erl | wc -l`

echo -n "Core: "
echo $core

echo -n "Controllers: "
echo $controllers

echo -n "Helpers: "
echo $helpers

echo -n "Models: "
echo $models

echo -n "Backends: "
echo $backends

echo -n "Tests: "
echo $tests

echo

echo -n "Total without tests: "
echo "$core+$controllers+$helpers+$models+$backends" | bc

echo -n "Total: "
echo "$core+$controllers+$helpers+$models+$backends+$tests" | bc
